# dbt_project.yml
name: 'maritime_pipeline'
version: '1.0.0'
config-version: 2

profile: 'maritime_pipeline'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # dbt artifacts

models:
  maritime_pipeline:
    silver:
      +materialized: view
      +schema: silver
    gold:
      +materialized: incremental
      +schema: gold
      # Config for specific models
      voyages:
        +post-hook: "DELETE FROM {{ this }} WHERE duration_hrs <= 0"
    preentation:
      +materialized: table
      +schema: analytics

  dbt_artifacts:
    +schema: operations
    +database: my_voyage_db  # Ensure it lands in MotherDuck
