maritime_pipeline:
  target: prod
  outputs:
    prod:
      type: duckdb
      # Connect to the MotherDuck database we created in ingestion
      path: 'md:my_voyage_db'
      schema: main
      threads: 4
      token: '{{ env_var("MOTHERDUCK_TOKEN") }}'
